// cards.js - flashcard seed deck. [subject code, question, answer]  P=Physics C=Chemistry M=Maths
window.flashSeed = [
["P","Coulomb's law (magnitude)","F = k q₁q₂ / r², with k = 1/4πε₀ ≈ 9×10⁹ N·m²/C²"],
["P","Electric field of a point charge","E = kq / r², directed radially outward for +q"],
["P","Gauss's law","∮E·dA = q_enclosed / ε₀"],
["P","Capacitance of a parallel-plate capacitor","C = ε₀A/d (with a dielectric filling it: C = Kε₀A/d)"],
["P","Energy stored in a capacitor","U = ½CV² = Q²/2C = ½QV"],
["P","Potential due to a point charge","V = kq / r (a scalar)"],
["P","Relation between E and V","E = −dV/dr"],
["P","Capacitors in series and parallel","Series: 1/C = Σ1/Cᵢ. Parallel: C = ΣCᵢ"],
["P","Drift velocity","v_d = I / (nAe)"],
["P","Ohm's law and resistivity","V = IR and R = ρl/A"],
["P","Kirchhoff's laws","KCL: ΣI = 0 at a junction. KVL: ΣV = 0 around a closed loop"],
["P","Biot–Savart law","dB = (μ₀/4π) · I dl × r̂ / r²"],
["P","Magnetic field of a long straight wire","B = μ₀I / (2πr)"],
["P","Lorentz force","F = q(E + v × B)"],
["P","Faraday's law of induction","ε = −dΦ/dt"],
["P","Energy stored in an inductor","U = ½LI²"],
["P","RMS values in AC","I_rms = I₀/√2 and V_rms = V₀/√2"],
["P","Impedance of a series LCR circuit; resonance","Z = √(R² + (X_L − X_C)²); resonance at ω = 1/√(LC)"],
["P","Lens maker's formula","1/f = (n − 1)(1/R₁ − 1/R₂)"],
["P","Lens formula (Cartesian sign convention)","1/v − 1/u = 1/f"],
["P","Fringe width in Young's double slit","β = λD / d"],
["P","Einstein's photoelectric equation","KE_max = hν − φ"],
["P","de Broglie wavelength","λ = h/p = h/mv"],
["P","Bohr model: hydrogen energy levels and radii","Eₙ = −13.6 eV / n²; rₙ ≈ 0.529 n² Å"],
["P","Radioactive decay law and half-life","N = N₀e^(−λt); T½ = 0.693/λ"],
["P","Newton's second law (momentum form)","F = dp/dt"],
["P","Escape velocity","v_e = √(2GM/R) ≈ 11.2 km/s for Earth"],
["P","Time period of a spring-mass system and a simple pendulum","T = 2π√(m/k); T = 2π√(l/g)"],
["P","Work–energy theorem","W_net = ΔKE"],
["P","Moments of inertia: ring, disc, solid sphere","Ring (axis ⟂ plane) MR²; disc ½MR²; solid sphere (diameter) (2/5)MR²"],
["P","Bernoulli's equation","P + ½ρv² + ρgh = constant"],
["P","First law of thermodynamics","ΔU = Q − W"],
["P","Adiabatic process relation","PV^γ = constant, where γ = Cp/Cv"],
["P","RMS speed of gas molecules","v_rms = √(3RT/M)"],
["P","Snell's law","n₁ sinθ₁ = n₂ sinθ₂"],
["C","Mole concept relations","moles = mass / molar mass = N / N_A, with N_A = 6.022×10²³"],
["C","Ideal gas equation and R","PV = nRT; R = 0.0821 L·atm/mol·K = 8.314 J/mol·K"],
["C","Heisenberg uncertainty principle","Δx · Δp ≥ h/4π"],
["C","Rydberg formula for hydrogen spectrum","1/λ = R_H (1/n₁² − 1/n₂²), R_H ≈ 1.097×10⁷ m⁻¹"],
["C","The four quantum numbers","n (shell), l (0 to n−1), m_l (−l to +l), m_s (±½)"],
["C","Aufbau, Hund and Pauli rules","Aufbau: fill lowest energy first. Hund: maximise unpaired spins in degenerate orbitals. Pauli: no two electrons share all four quantum numbers"],
["C","Bond order from MO theory","(Nb − Na) / 2"],
["C","Hybridisation and shape of SF₆ and XeF₄","SF₆: sp³d², octahedral. XeF₄: sp³d², square planar"],
["C","Relation between ΔH and ΔU","ΔH = ΔU + Δn_g RT"],
["C","Gibbs energy and spontaneity","ΔG = ΔH − TΔS; spontaneous when ΔG < 0; ΔG° = −RT ln K"],
["C","Hess's law","Total enthalpy change depends only on initial and final states, not the path"],
["C","Relation between Kp and Kc","Kp = Kc (RT)^Δn"],
["C","pH and pOH","pH = −log[H⁺]; at 25 °C, pH + pOH = 14"],
["C","Henderson–Hasselbalch equation (acidic buffer)","pH = pKa + log([salt]/[acid])"],
["C","Ksp for a salt AₓB_y","Ksp = (xs)ˣ (ys)ʸ, where s is the molar solubility"],
["C","Nernst equation at 298 K","E = E° − (0.0591/n) log Q"],
["C","Relation between ΔG° and cell EMF","ΔG° = −nFE°"],
["C","Faraday's first law of electrolysis","m = ZIt = (M/nF) · It"],
["C","First-order rate constant and half-life","k = (2.303/t) log([A]₀/[A]); t½ = 0.693/k"],
["C","Arrhenius equation","k = A e^(−Ea/RT)"],
["C","Raoult's law","p_A = x_A · p°_A"],
["C","Colligative property formulas","ΔT_b = i K_b m; ΔT_f = i K_f m; π = iCRT"],
["C","Spin-only magnetic moment","μ = √(n(n+2)) BM, n = number of unpaired electrons"],
["C","SN1 versus SN2","SN2: bimolecular, one step, inversion, favoured by 1° halides. SN1: unimolecular, carbocation, racemisation, favoured by 3°"],
["C","Markovnikov's rule","In HX addition to an alkene, H goes to the carbon already holding more H atoms (more stable carbocation forms)"],
["C","Grignard reagent with carbonyls","With HCHO gives 1° alcohol; other aldehydes give 2°; ketones give 3° alcohols"],
["C","Hoffmann bromamide reaction","RCONH₂ + Br₂ + 4NaOH → RNH₂ + Na₂CO₃ + 2NaBr + 2H₂O (amine has one carbon less)"],
["C","Aldol condensation","Carbonyls with α-H, dilute base → β-hydroxy carbonyl, then α,β-unsaturated carbonyl on heating"],
["C","Cannizzaro reaction","Aldehydes with no α-H in conc. alkali → alcohol + carboxylate (disproportionation)"],
["C","Tollens' test","Aldehydes give a silver mirror; ketones do not"],
["C","Hückel's rule","Planar, cyclic, fully conjugated with (4n + 2) π electrons → aromatic"],
["C","Maximum stereoisomers","With n different stereocentres: up to 2ⁿ stereoisomers"],
["C","Lanthanoid contraction","Gradual decrease in ionic radius from La³⁺ to Lu³⁺ due to poor shielding by 4f electrons"],
["C","Ionisation energy trend","Increases across a period, decreases down a group (exceptions: Be > B, N > O)"],
["C","Molarity versus molality","Molarity = mol solute / L solution (temperature dependent). Molality = mol solute / kg solvent (not)"],
["M","Roots of a quadratic","x = (−b ± √(b² − 4ac)) / 2a; sum = −b/a; product = c/a"],
["M","Nature of roots from discriminant","D > 0 real and distinct; D = 0 real and equal; D < 0 complex conjugates"],
["M","AP: nth term and sum","aₙ = a + (n−1)d; Sₙ = (n/2)[2a + (n−1)d]"],
["M","GP: nth term, sum, infinite sum","aₙ = arⁿ⁻¹; Sₙ = a(rⁿ−1)/(r−1); S∞ = a/(1−r) for |r| < 1"],
["M","AM–GM inequality","For positive numbers, AM ≥ GM, with equality when all are equal"],
["M","General term of binomial expansion","T_{r+1} = ⁿC_r · aⁿ⁻ʳ · bʳ"],
["M","Permutations and combinations","ⁿP_r = n!/(n−r)!; ⁿC_r = n!/(r!(n−r)!)"],
["M","Sum of binomial coefficients","ΣⁿC_r = 2ⁿ"],
["M","Euler's formula","e^(iθ) = cosθ + i sinθ"],
["M","Modulus and conjugate relation","z · z̄ = |z|²"],
["M","De Moivre's theorem","(cosθ + i sinθ)ⁿ = cos nθ + i sin nθ"],
["M","Cube roots of unity","1 + ω + ω² = 0 and ω³ = 1"],
["M","sin(A + B)","sinA cosB + cosA sinB"],
["M","cos 2A (three forms)","cos²A − sin²A = 2cos²A − 1 = 1 − 2sin²A"],
["M","tan(A + B)","(tanA + tanB) / (1 − tanA tanB)"],
["M","sin 3A","3 sinA − 4 sin³A"],
["M","Principal value ranges","sin⁻¹: [−π/2, π/2]; cos⁻¹: [0, π]; tan⁻¹: (−π/2, π/2)"],
["M","Standard limits at 0","sin x / x → 1; (eˣ − 1)/x → 1; (1 + x)^(1/x) → e"],
["M","Product rule","d/dx (uv) = u′v + uv′"],
["M","Derivatives of tan x and sec x","d/dx tan x = sec²x; d/dx sec x = sec x tan x"],
["M","Basic integrals of 1/x and eˣ","∫1/x dx = ln|x| + C; ∫eˣ dx = eˣ + C"],
["M","∫ dx / (a² + x²)","(1/a) tan⁻¹(x/a) + C"],
["M","∫ dx / √(a² − x²)","sin⁻¹(x/a) + C"],
["M","Integration by parts and ILATE","∫u v dx = u∫v dx − ∫(u′ ∫v dx) dx; choose u by ILATE (Inverse, Log, Algebraic, Trig, Exponential)"],
["M","King's property of definite integrals","∫₀ᵃ f(x) dx = ∫₀ᵃ f(a − x) dx"],
["M","Even and odd functions over [−a, a]","2∫₀ᵃ f dx if f is even; 0 if f is odd"],
["M","Linear differential equation","dy/dx + Py = Q; IF = e^(∫P dx); y · IF = ∫Q · IF dx + C"],
["M","Distance from a point to a line","|Ax₁ + By₁ + C| / √(A² + B²)"],
["M","Circle: equations and radius","(x−h)² + (y−k)² = r²; general form x² + y² + 2gx + 2fy + c = 0 with r = √(g² + f² − c)"],
["M","Parabola y² = 4ax","Focus (a, 0), directrix x = −a, latus rectum 4a"],
["M","Ellipse x²/a² + y²/b² = 1","e = √(1 − b²/a²); foci (±ae, 0)"],
["M","Hyperbola x²/a² − y²/b² = 1","e = √(1 + b²/a²); asymptotes y = ±(b/a)x"],
["M","Dot and cross product magnitudes","a·b = |a||b| cosθ; |a × b| = |a||b| sinθ"],
["M","Scalar triple product","[a b c] = a·(b × c) = volume of the parallelepiped"],
["M","Determinant and adjoint properties","|AB| = |A||B|; |kA| = kⁿ|A| for n×n; A · adj A = |A| I"],
["M","Inverse of a matrix","A⁻¹ = adj(A) / |A|"],
["M","Bayes' theorem","P(Eᵢ|A) = P(Eᵢ)P(A|Eᵢ) / Σⱼ P(Eⱼ)P(A|Eⱼ)"],
["M","Binomial distribution","P(X = r) = ⁿC_r pʳ qⁿ⁻ʳ; mean np; variance npq"],
["M","Distance between skew lines","|(a₂ − a₁)·(b₁ × b₂)| / |b₁ × b₂|"],
["M","Angle between two lines in 3D","cosθ = |a₁a₂ + b₁b₂ + c₁c₂| / (√(a₁²+b₁²+c₁²) · √(a₂²+b₂²+c₂²))"],
["P","Torque","τ = r × F = Iα"],
["P","Angular momentum","L = Iω = r × p; conserved if net torque = 0"],
["P","Rolling without slipping","v = ωR; KE = ½mv²(1 + k²/R²)"],
["P","Kepler's third law","T² ∝ r³ (T² = 4π²r³/GM)"],
["P","Orbital velocity","v₀ = √(GM/r)"],
["P","Gravitational potential energy","U = −GMm/r"],
["P","Young's modulus","Y = stress/strain = (F/A)/(ΔL/L)"],
["P","Stokes' law","F = 6πηrv"],
["P","Terminal velocity","v_T = 2r²(ρ−σ)g / 9η"],
["P","Surface tension: excess pressure in a bubble","Drop: 2T/R. Soap bubble: 4T/R"],
["P","Doppler effect (sound)","f′ = f (v ± v_o)/(v ∓ v_s)"],
["P","Speed of a wave on a string","v = √(T/μ)"],
["P","Fundamental frequency of a closed organ pipe","f = v/4L (odd harmonics only)"],
["P","Intensity level of sound","β = 10 log₁₀(I/I₀) dB, I₀ = 10⁻¹² W/m²"],
["P","Heat conduction rate","dQ/dt = kA(ΔT)/L"],
["P","Stefan–Boltzmann law","P = σAeT⁴"],
["P","Wien's displacement law","λ_max T = b ≈ 2.9×10⁻³ m·K"],
["P","Carnot efficiency","η = 1 − T₂/T₁"],
["P","Work done in isothermal expansion","W = nRT ln(V₂/V₁)"],
["P","Mayer's relation","Cp − Cv = R"],
["P","Mirror formula","1/v + 1/u = 1/f; f = R/2"],
["P","Prism deviation (minimum)","n = sin((A+δ_m)/2) / sin(A/2)"],
["P","Brewster's law","tan θ_B = n"],
["P","Single-slit minima","a sinθ = nλ"],
["P","Transformer relation","V_s/V_p = N_s/N_p = I_p/I_s (ideal)"],
["P","Mutual inductance and emf","ε = −M dI/dt"],
["P","Force between parallel wires","F/l = μ₀I₁I₂/2πd"],
["P","Torque on a magnetic dipole","τ = M × B; U = −M·B"],
["P","Cyclotron radius","r = mv/qB"],
["P","Binding energy","BE = Δm c² (931.5 MeV per u)"],
["P","Nuclear radius","R = R₀A^(1/3), R₀ ≈ 1.2 fm"],
["P","Moseley's law","√ν = a(Z − b)"],
["P","Potential barrier: p-n junction depletion","Forward bias narrows depletion region; reverse bias widens it"],
["P","Logic gates: NAND and NOR","Universal gates; NAND = (A·B)′, NOR = (A+B)′"],
["C","Dalton's law of partial pressures","P_total = ΣPᵢ; Pᵢ = xᵢP_total"],
["C","Graham's law","r₁/r₂ = √(M₂/M₁)"],
["C","van der Waals equation","(P + an²/V²)(V − nb) = nRT"],
["C","Average, rms and most probable speeds","u_mp : u_av : u_rms = √2 : √(8/π) : √3"],
["C","Bragg's equation","nλ = 2d sinθ"],
["C","Packing efficiency: SC, BCC, FCC","52.4%, 68%, 74%"],
["C","Atoms per unit cell","SC 1, BCC 2, FCC 4"],
["C","Density of a unit cell","ρ = ZM / (a³N_A)"],
["C","de Broglie and Bohr quantisation","mvr = nh/2π"],
["C","Radial nodes and angular nodes","Radial = n − l − 1; angular = l"],
["C","Electronegativity order of halogens","F > Cl > Br > I"],
["C","Fajans' rules","Small cation, large anion, high charges → more covalent character"],
["C","Dipole moment","μ = q × d (Debye); zero for symmetric molecules like CO₂, BF₃"],
["C","VSEPR: shape of NH₃, H₂O, CH₄","NH₃ pyramidal; H₂O bent; CH₄ tetrahedral"],
["C","Enthalpy of reaction from bond energies","ΔH = Σ(bonds broken) − Σ(bonds formed)"],
["C","Entropy change","ΔS = q_rev/T; ΔS_univ > 0 for spontaneous processes"],
["C","Le Chatelier's principle","A system at equilibrium opposes any applied change"],
["C","Degree of dissociation and Kp","For A ⇌ 2B starting with 1 mol: Kp = 4α²P/(1 − α²)"],
["C","Ostwald's dilution law","K_a = Cα² (for weak electrolytes, α ≪ 1: α = √(K_a/C))"],
["C","Common ion effect","Adding a common ion suppresses ionisation/solubility"],
["C","Hydrolysis of salt: pH of weak acid + strong base","pH = ½(pK_w + pK_a + log C)"],
["C","Kohlrausch's law","Λ°m = λ°₊ + λ°₋ (independent migration of ions)"],
["C","Molar conductivity","Λm = κ × 1000 / C (S cm² mol⁻¹, C in mol/L)"],
["C","Zero-order reaction","[A] = [A]₀ − kt; t½ = [A]₀/2k"],
["C","Order and molecularity","Order is experimental and can be fractional; molecularity is theoretical, a whole number"],
["C","Langmuir/Freundlich adsorption isotherm","Freundlich: x/m = kP^(1/n)"],
["C","Oxidation state of Cr in K₂Cr₂O₇ and Mn in KMnO₄","+6 and +7"],
["C","Crystal field splitting in octahedral complexes","t₂g lower, e_g higher; strong field → low spin"],
["C","EAN rule","EAN = Z − oxidation state + 2 × coordination number"],
["C","Wilkinson's catalyst and Zeigler–Natta catalyst","[RhCl(PPh₃)₃] for hydrogenation; TiCl₄ + Al(C₂H₅)₃ for polymerisation"],
["C","Reimer–Tiemann reaction","Phenol + CHCl₃ + NaOH → salicylaldehyde"],
["C","Kolbe's reaction","Sodium phenoxide + CO₂, then H⁺ → salicylic acid"],
["C","Friedel–Crafts alkylation and acylation","Benzene + RCl/AlCl₃ → alkylbenzene; + RCOCl/AlCl₃ → aryl ketone"],
["C","Sandmeyer reaction","ArN₂⁺Cl⁻ + CuCl/CuBr → ArCl/ArBr"],
["C","Gabriel phthalimide synthesis","Gives pure primary aliphatic amines only"],
["C","Lucas test","ROH + ZnCl₂/conc. HCl: turbidity fastest for 3°, slower 2°, none (at RT) for 1°"],
["C","Iodoform test","Positive for CH₃CO– and CH₃CH(OH)– groups: yellow ppt of CHI₃"],
["C","Wolff–Kishner and Clemmensen reductions","C=O → CH₂ under basic (NH₂NH₂/KOH) and acidic (Zn–Hg/HCl) conditions"],
["C","Carbocation stability order","3° > 2° > 1° > CH₃⁺ (hyperconjugation and +I)"],
["C","Acidic strength of carboxylic acids","EWG increases acidity; EDG decreases it"],
["C","Reducing vs non-reducing sugars","Sucrose is non-reducing; glucose and maltose are reducing"],
["C","Zwitterion and isoelectric point","Amino acid with both charges; pI = ½(pKa₁ + pKa₂)"],
["M","Sum of squares and cubes","Σn² = n(n+1)(2n+1)/6; Σn³ = [n(n+1)/2]²"],
["M","Relation between AM, GM, HM","AM·HM = GM²; AM ≥ GM ≥ HM"],
["M","Condition for common root of two quadratics","(c₁a₂ − c₂a₁)² = (a₁b₂ − a₂b₁)(b₁c₂ − b₂c₁)"],
["M","Number of derangements","D_n = n! Σ (−1)ᵏ/k!"],
["M","Circular permutations","(n − 1)!; for necklaces (n − 1)!/2"],
["M","Binomial coefficient identity","ⁿC_r + ⁿC_{r−1} = ⁿ⁺¹C_r"],
["M","Roots of z^n = 1","z_k = e^(2πik/n), k = 0,…,n−1"],
["M","Triangle inequality for complex numbers","|z₁ + z₂| ≤ |z₁| + |z₂|"],
["M","Sine rule and cosine rule","a/sinA = 2R; c² = a² + b² − 2ab cosC"],
["M","Area of a triangle","½ab sinC = √(s(s−a)(s−b)(s−c)) = rs"],
["M","Sum of sines/cosines to products","sinC + sinD = 2 sin((C+D)/2) cos((C−D)/2)"],
["M","General solutions","sinθ = sinα → θ = nπ + (−1)ⁿα; cosθ = cosα → θ = 2nπ ± α; tanθ = tanα → θ = nπ + α"],
["M","L'Hôpital's rule","If 0/0 or ∞/∞: lim f/g = lim f′/g′"],
["M","Rolle's and Lagrange's mean value theorems","Rolle: f′(c) = 0. LMVT: f′(c) = (f(b) − f(a))/(b − a)"],
["M","Derivative of inverse trig: sin⁻¹x and tan⁻¹x","1/√(1 − x²) and 1/(1 + x²)"],
["M","Quotient and chain rule","(u/v)′ = (u′v − uv′)/v²; (f(g))′ = f′(g)·g′"],
["M","Curve tangent and normal slope","Tangent slope = dy/dx; normal slope = −1/(dy/dx)"],
["M","Condition for maxima/minima","f′ = 0; f″ < 0 maximum; f″ > 0 minimum"],
["M","Area between curves","∫ₐᵇ |f(x) − g(x)| dx"],
["M","Wallis formula idea: ∫₀^{π/2} sinⁿx dx","(n−1)(n−3)…/n(n−2)… × (π/2 if n even)"],
["M","∫ sec x dx","ln|sec x + tan x| + C"],
["M","∫ dx/(x² − a²)","(1/2a) ln|(x − a)/(x + a)| + C"],
["M","Variable separable ODE","dy/dx = f(x)g(y) → ∫dy/g(y) = ∫f(x)dx"],
["M","Order and degree of an ODE","Order = highest derivative; degree = its power (after clearing radicals)"],
["M","Section formula","Internal: ((mx₂+nx₁)/(m+n), (my₂+ny₁)/(m+n))"],
["M","Equation of tangent to a circle","xx₁ + yy₁ = r² at (x₁, y₁) on x² + y² = r²"],
["M","Length of tangent from a point","√(S₁) = √(x₁² + y₁² + 2gx₁ + 2fy₁ + c)"],
["M","Tangent to y² = 4ax with slope m","y = mx + a/m"],
["M","Eccentricity classification of conics","e < 1 ellipse; e = 1 parabola; e > 1 hyperbola"],
["M","Equation of a plane","ax + by + cz + d = 0; normal vector (a, b, c)"],
["M","Distance from a point to a plane","|ax₁+by₁+cz₁+d| / √(a²+b²+c²)"],
["M","Vector projection","Projection of a on b = (a·b)/|b|"],
["M","Rank/Cramer's rule","x = D_x/D, y = D_y/D if D ≠ 0"],
["M","Probability of at least one","P = 1 − P(none)"],
["M","Conditional probability","P(A|B) = P(A∩B)/P(B)"],
["M","Variance of a data set","σ² = Σ(xᵢ − x̄)²/n = Σxᵢ²/n − x̄²"],
["M","Domain of sin⁻¹ and cos⁻¹","[−1, 1]"],
["M","Relations: equivalence","Reflexive, symmetric and transitive"],
["M","Number of functions, one-one, onto","|A| = m, |B| = n: nᵐ total; ⁿP_m one-one (n ≥ m)"]
];
