// cards2.js - extra flashcards (P=Physics C=Chemistry M=Maths). Loaded after cards.js; appends to window.flashSeed.
(function () {
const X = [
/* ---------- PHYSICS: mechanics ---------- */
["P","Equations of motion (constant acceleration)","v = u + at; s = ut + ½at²; v² = u² + 2as"],
["P","Projectile: time of flight, range, max height","T = 2u sinθ/g; R = u² sin2θ/g; H = u² sin²θ/2g"],
["P","Centripetal acceleration and force","a = v²/r = ω²r; F = mv²/r"],
["P","Banking of roads (no friction)","tanθ = v²/(rg)"],
["P","Friction laws and angle of repose","f_s ≤ μ_sN; f_k = μ_kN; angle of repose: tanθ = μ_s"],
["P","Impulse–momentum theorem","J = F·Δt = Δp"],
["P","Final velocities in a 1-D elastic collision","v₁ = [(m₁−m₂)u₁ + 2m₂u₂]/(m₁+m₂); v₂ = [(m₂−m₁)u₂ + 2m₁u₁]/(m₁+m₂)"],
["P","Coefficient of restitution","e = (v₂ − v₁)/(u₁ − u₂); e = 1 elastic, e = 0 perfectly inelastic"],
["P","Power in terms of force and velocity","P = dW/dt = F·v"],
["P","Elastic potential energy of a spring","U = ½kx²"],
["P","Gravitational potential energy and potential","U = −GMm/r; V = −GM/r"],
["P","Orbital velocity and time period of a satellite","v₀ = √(GM/r) (= √(gR) ≈ 7.9 km/s near Earth); T = 2π√(r³/GM)"],
["P","Kepler's three laws","1) elliptical orbits, Sun at a focus; 2) equal areas in equal times (L conserved); 3) T² ∝ a³"],
["P","Variation of g with height and depth","Height h ≪ R: g′ ≈ g(1 − 2h/R). Depth d: g′ = g(1 − d/R)"],
["P","Torque and Newton's law for rotation","τ = r × F = Iα"],
["P","Angular momentum","L = r × p = Iω; conserved if net external torque is zero"],
["P","Kinetic energy of rolling without slipping","KE = ½mv²(1 + k²/R²), with v = ωR"],
["P","Parallel and perpendicular axis theorems","I = I_cm + Md²; for a planar lamina I_z = I_x + I_y"],
["P","Moment of inertia of a thin rod","About centre: ML²/12; about an end: ML²/3"],
["P","Young's modulus, bulk modulus, shear modulus","Y = (F/A)/(Δl/l); B = −VΔP/ΔV; η = (F/A)/θ"],
["P","Elastic energy stored per unit volume","½ × stress × strain"],
["P","Stokes' law and terminal velocity","F = 6πηrv; v_t = 2r²(ρ − σ)g / 9η"],
["P","Excess pressure: liquid drop, soap bubble","Drop: 2T/R; soap bubble (two surfaces): 4T/R"],
["P","Capillary rise","h = 2T cosθ / (ρ g r)"],
["P","Equation of continuity and Torricelli's theorem","A₁v₁ = A₂v₂; speed of efflux v = √(2gh)"],
["P","Displacement, velocity and acceleration in SHM","x = A sin(ωt + φ); v = ω√(A² − x²); a = −ω²x"],
["P","Total energy in SHM","E = ½mω²A² = ½kA²"],
["P","Speed of a transverse wave on a string","v = √(T/μ)"],
["P","Speed of sound in a gas","v = √(γP/ρ)"],
["P","Resonant frequencies: string and pipes","String / open pipe: fₙ = nv/2L. Closed pipe: f = (2n−1)v/4L (odd harmonics only)"],
["P","Doppler effect","f′ = f (v ± v_o)/(v ∓ v_s) (upper signs: approach)"],
["P","Beat frequency","f_beat = |f₁ − f₂|"],
["P","Sound intensity level","β = 10 log₁₀(I/I₀), I₀ = 10⁻¹² W/m²"],
/* ---------- PHYSICS: thermal ---------- */
["P","Heat transfer relations","Q = mcΔT (no phase change); Q = mL (phase change)"],
["P","Thermal expansion coefficients","ΔL = αLΔT; β = 2α (area); γ = 3α (volume)"],
["P","Newton's law of cooling","dT/dt = −k(T − T₀)"],
["P","Stefan–Boltzmann law","P = σAeT⁴, σ = 5.67×10⁻⁸ W m⁻² K⁻⁴"],
["P","Wien's displacement law","λ_m T = 2.898×10⁻³ m·K"],
["P","Rate of heat conduction","Q/t = kA(T₁ − T₂)/L"],
["P","Efficiency of a Carnot engine","η = 1 − T₂/T₁ (temperatures in kelvin)"],
["P","Work done in isothermal process","W = nRT ln(V₂/V₁)"],
["P","Mayer's relation and γ","Cp − Cv = R; γ = 1 + 2/f (f = degrees of freedom)"],
["P","γ for monatomic and diatomic gases","Monatomic: f = 3, γ = 5/3. Diatomic (rigid): f = 5, γ = 7/5"],
["P","Equipartition and internal energy","½kT per degree of freedom; U = (f/2)nRT"],
["P","Work in an adiabatic process","W = (P₁V₁ − P₂V₂)/(γ − 1) = nR(T₁ − T₂)/(γ − 1)"],
/* ---------- PHYSICS: electromagnetism ---------- */
["P","Electric dipole: moment, axial and equatorial field","p = qd; axial E = 2kp/r³; equatorial E = kp/r³"],
["P","Torque and potential energy of a dipole in a field","τ = p × E; U = −p·E"],
["P","Field of infinite sheet and conductor surface","Sheet: σ/2ε₀. Just outside a conductor: σ/ε₀"],
["P","Field of an infinite line charge","E = λ / (2πε₀r)"],
["P","Energy density of an electric field","u = ½ε₀E²"],
["P","Capacitance of isolated and spherical capacitor","Isolated sphere: 4πε₀R. Concentric spheres: 4πε₀ab/(b − a)"],
["P","Force between capacitor plates","F = Q²/(2ε₀A)"],
["P","Wheatstone bridge balance","P/Q = R/S (galvanometer shows no deflection)"],
["P","Potentiometer: internal resistance of a cell","r = R(l₁ − l₂)/l₂"],
["P","Meter bridge unknown resistance","X = R(100 − l)/l"],
["P","Electric power in a resistor","P = VI = I²R = V²/R"],
["P","Temperature dependence of resistance","R_t = R₀(1 + αΔT)"],
["P","Terminal voltage of a cell","V = ε − Ir (discharging)"],
["P","Maximum power transfer theorem","Load power is maximum when R = r (internal resistance)"],
["P","Magnetic force on a current-carrying wire","F = BIL sinθ"],
["P","Torque on a current loop","τ = NIAB sinθ"],
["P","Magnetic field of a circular loop","Centre: μ₀I/2R. On axis: μ₀IR² / [2(R² + x²)^(3/2)]"],
["P","Magnetic field inside a solenoid and toroid","Solenoid: B = μ₀nI. Toroid: B = μ₀NI/2πr"],
["P","Ampere's circuital law","∮B·dl = μ₀I_enclosed"],
["P","Cyclotron: radius and frequency","r = mv/qB; f = qB/2πm (independent of speed)"],
["P","Converting a galvanometer","Ammeter: shunt S = I_gG/(I − I_g). Voltmeter: series R = V/I_g − G"],
["P","Magnetic moment of a revolving electron","μ = −(e/2m)L; Bohr magneton = 9.27×10⁻²⁴ A·m²"],
["P","Motional emf","ε = Blv"],
["P","Self-inductance relations","ε = −L dI/dt; solenoid L = μ₀n²Al"],
["P","Mutual inductance","ε₂ = −M dI₁/dt"],
["P","Ideal transformer","V_s/V_p = N_s/N_p = I_p/I_s"],
["P","Power factor and average AC power","cosφ = R/Z; P_avg = V_rms I_rms cosφ"],
["P","Displacement current","I_d = ε₀ dΦ_E/dt"],
["P","Speed of EM waves and E/B ratio","c = 1/√(μ₀ε₀); E₀/B₀ = c"],
["P","Order of the EM spectrum (low to high frequency)","Radio, microwave, infrared, visible, ultraviolet, X-ray, gamma"],
["P","Diamagnetic, paramagnetic, ferromagnetic","Dia: χ small negative. Para: small positive, ∝ 1/T (Curie). Ferro: large positive, hysteresis, Curie temperature"],
/* ---------- PHYSICS: optics ---------- */
["P","Mirror formula","1/v + 1/u = 1/f, with f = R/2"],
["P","Refraction at a spherical surface","n₂/v − n₁/u = (n₂ − n₁)/R"],
["P","Power of a lens and combinations","P = 1/f (in metres, unit dioptre); lenses in contact: P = P₁ + P₂"],
["P","Critical angle and total internal reflection","sin C = 1/n (light going denser → rarer, angle of incidence > C)"],
["P","Prism formula","n = sin[(A + δ_m)/2] / sin(A/2); δ = i + e − A"],
["P","Brewster's law","tanθ_B = n; reflected light is fully plane polarised"],
["P","Malus' law","I = I₀cos²θ"],
["P","Single-slit diffraction","Minima: a sinθ = nλ; central maximum width 2λD/a"],
["P","Rayleigh criterion for resolution","θ_min = 1.22 λ/D"],
["P","Young's double slit: maxima and minima","Path difference nλ → bright; (n + ½)λ → dark"],
["P","Magnification of microscope and telescope","Telescope: m = f_o/f_e. Compound microscope: m ≈ (L/f_o)(D/f_e)"],
/* ---------- PHYSICS: modern ---------- */
["P","Photon energy","E = hν = hc/λ ≈ 12400/λ(Å) eV"],
["P","Stopping potential and threshold","eV₀ = KE_max; φ = hν₀"],
["P","Bragg's law","2d sinθ = nλ"],
["P","Nuclear radius","R = R₀A^(1/3), R₀ ≈ 1.2 fm (so density is constant)"],
["P","Binding energy and mass defect","BE = Δm·c²; 1 u = 931.5 MeV"],
["P","Activity and mean life","A = λN = −dN/dt; τ = 1/λ = T½/0.693"],
["P","Change in A and Z in decays","α: A − 4, Z − 2. β⁻: Z + 1. β⁺: Z − 1. γ: no change"],
["P","Energy levels of hydrogen-like ions","Eₙ = −13.6 Z²/n² eV; vₙ = 2.18×10⁶ Z/n m/s"],
["P","p-type and n-type semiconductors","p-type: trivalent dopant, holes majority. n-type: pentavalent dopant, electrons majority"],
["P","Zener diode use","Voltage regulation in reverse breakdown"],
["P","Universal logic gates","NAND and NOR (any gate can be built from either)"],
["P","Transistor current gains","α = I_C/I_E; β = I_C/I_B; β = α/(1 − α)"],
["P","Amplitude vs frequency modulation","AM: carrier amplitude varies with signal; FM: carrier frequency varies. Modulation index μ = A_m/A_c"],
/* ---------- PHYSICS: units & errors ---------- */
["P","Dimensional formulae: G, h, energy","G: M⁻¹L³T⁻²; h: ML²T⁻¹; energy: ML²T⁻²"],
["P","Dimensions of ε₀ and μ₀","ε₀: M⁻¹L⁻³T⁴A²; μ₀: MLT⁻²A⁻²"],
["P","Vernier and screw gauge least count","Vernier: 1 MSD − 1 VSD. Screw gauge: pitch / number of circular divisions"],
["P","Error propagation for x = aᵖbᑫ","Δx/x = p(Δa/a) + q(Δb/b) (maximum error)"],
/* ---------- CHEMISTRY: physical ---------- */
["C","Dalton's law of partial pressures","P_total = ΣPᵢ; Pᵢ = xᵢ·P_total"],
["C","Graham's law of diffusion","r₁/r₂ = √(M₂/M₁) at same T and P"],
["C","van der Waals equation","(P + an²/V²)(V − nb) = nRT"],
["C","Compressibility factor","Z = PV/nRT; Z < 1: attraction dominates, Z > 1: repulsion dominates"],
["C","Critical constants in van der Waals terms","T_c = 8a/27Rb; P_c = a/27b²; V_c = 3b"],
["C","Molecular speeds ratio","u_mp : u_avg : u_rms = √2 : √(8/π) : √3 = 1 : 1.128 : 1.224"],
["C","Nodes in an orbital","Radial nodes = n − l − 1; angular nodes = l; total nodes = n − 1"],
["C","Maximum electrons in a shell and subshell","Shell: 2n². Subshells s, p, d, f hold 2, 6, 10, 14"],
["C","Exceptional electronic configurations","Cr: [Ar]3d⁵4s¹; Cu: [Ar]3d¹⁰4s¹ (half/full d stability)"],
["C","Electron gain enthalpy anomaly","Cl has a more negative value than F (small size of F, repulsion)"],
["C","Order of electronegativity","F > O > N ≈ Cl > Br > C ≈ S ≈ I > H"],
["C","Fajans' rules","Covalent character increases with small, highly charged cation and large, easily polarised anion"],
["C","Lattice energy dependence","Increases with ionic charges and decreases with ionic size: U ∝ q₁q₂/r"],
["C","Bond angles: CH₄, NH₃, H₂O","CH₄ 109.5°; NH₃ 107°; H₂O 104.5° (lone-pair repulsion)"],
["C","Shapes: BF₃, PCl₅, ClF₃, XeF₂, SF₄, IF₇","BF₃ trigonal planar; PCl₅ trigonal bipyramidal; ClF₃ T-shaped; XeF₂ linear; SF₄ see-saw; IF₇ pentagonal bipyramidal"],
["C","Magnetic behaviour of O₂ from MO theory","O₂: bond order 2, paramagnetic (2 unpaired e⁻). O₂⁻: 1.5; O₂²⁻: 1"],
["C","MO energy order for B₂, C₂, N₂ versus O₂, F₂","B₂–N₂: π(2p) below σ(2p). O₂, F₂: σ(2p) below π(2p)"],
["C","Dipole moment","μ = q × d (unit Debye); CO₂ and BF₃ are zero; NH₃ > NF₃"],
["C","Intramolecular vs intermolecular H-bonding","o-nitrophenol (intra): steam volatile, lower b.p. p-nitrophenol (inter): higher b.p."],
["C","Spectrochemical series","I⁻ < Br⁻ < Cl⁻ < F⁻ < OH⁻ < H₂O < NH₃ < en < CN⁻ < CO"],
["C","Crystal field splitting in octahedral complexes","t₂g: −0.4Δ₀ each; e_g: +0.6Δ₀ each. Strong field → low spin"],
["C","Effective atomic number (EAN)","EAN = Z − oxidation state + 2 × (number of ligands donating pairs)"],
["C","Types of isomerism in coordination compounds","Structural: ionisation, linkage, coordination, hydrate. Stereo: geometrical and optical"],
["C","IUPAC name of [Co(NH₃)₆]Cl₃","Hexaamminecobalt(III) chloride"],
["C","Entropy change","ΔS = q_rev/T; ΔS_universe > 0 for spontaneous processes"],
["C","Bond enthalpy and reaction enthalpy","ΔH = Σ(bonds broken) − Σ(bonds formed)"],
["C","van't Hoff equation for K versus T","ln(K₂/K₁) = (ΔH°/R)(1/T₁ − 1/T₂)"],
["C","Ostwald's dilution law","α = √(Ka/C); [H⁺] = √(Ka·C) for a weak acid"],
["C","pH of salt of weak acid and strong base","pH = ½(pKw + pKa + log C)"],
["C","Buffer capacity","Maximum when pH = pKa, i.e. [salt] = [acid]"],
["C","Precipitation criterion","Precipitate forms when ionic product Q > Ksp"],
["C","Kohlrausch law","Λ°m = ν₊λ°₊ + ν₋λ°₋; strong electrolytes Λm = Λ°m − A√c"],
["C","Conductivity and cell constant","κ = G·(l/A); cell constant = l/A; Λm = κ × 1000 / C (C in mol/L)"],
["C","Zero-order reaction","[A] = [A]₀ − kt; t½ = [A]₀/2k; rate is independent of concentration"],
["C","Second-order reaction","1/[A] = 1/[A]₀ + kt; t½ = 1/(k[A]₀)"],
["C","Slope of ln k vs 1/T","−Eₐ/R (or −Eₐ/2.303R for log₁₀ k)"],
["C","Order vs molecularity","Order is experimental (can be 0 or fractional); molecularity is theoretical (integer ≥ 1)"],
["C","Freundlich adsorption isotherm","x/m = kP^(1/n); at high pressure it becomes independent of P"],
["C","Hardy–Schulze rule","Coagulating power of an ion increases with its charge: Al³⁺ > Ba²⁺ > Na⁺ for negative sol"],
["C","Henry's law","p = K_H·x (mole fraction of gas in solution); higher K_H means lower solubility"],
["C","Azeotropes","Positive deviation → minimum boiling azeotrope. Negative deviation → maximum boiling azeotrope"],
["C","Van't Hoff factor for NaCl and K₂SO₄ (ideal)","NaCl: 2; K₂SO₄: 3. Association gives i < 1, dissociation gives i > 1"],
["C","Atoms per unit cell and packing efficiency","SC: 1, 52.4%; BCC: 2, 68%; FCC/HCP: 4, 74%"],
["C","Density of a crystal","d = Z·M / (a³·N_A)"],
["C","Edge length and radius relations","BCC: a = 4r/√3; FCC: a = 2√2 r; SC: a = 2r"],
["C","Schottky and Frenkel defects","Schottky: equal cations and anions missing, density decreases. Frenkel: ion moves to interstitial site, density unchanged"],
["C","Radius ratio and coordination number","0.225–0.414: tetrahedral (4); 0.414–0.732: octahedral (6); 0.732–1: cubic (8)"],
/* ---------- CHEMISTRY: inorganic ---------- */
["C","Diagonal relationships","Li–Mg, Be–Al, B–Si"],
["C","Flame test colours","Li crimson; Na golden yellow; K lilac; Ca brick red; Sr crimson; Ba apple green"],
["C","Solvay process","NaCl + NH₃ + CO₂ + H₂O → NaHCO₃ → Na₂CO₃ on heating"],
["C","Plaster of Paris","CaSO₄·½H₂O; sets to gypsum CaSO₄·2H₂O on adding water"],
["C","Haber process conditions","N₂ + 3H₂ ⇌ 2NH₃; Fe catalyst, ~450 °C, ~200 atm"],
["C","Ostwald process","4NH₃ + 5O₂ → 4NO + 6H₂O (Pt/Rh, 500 K) → NO₂ → HNO₃"],
["C","Contact process","2SO₂ + O₂ ⇌ 2SO₃ over V₂O₅; absorb in H₂SO₄ to form oleum"],
["C","Bleaching powder","CaOCl₂ (from Ca(OH)₂ + Cl₂); oxidising and bleaching agent"],
["C","Xenon compounds","XeF₂ (linear), XeF₄ (square planar), XeF₆ (distorted octahedral), XeO₃ (pyramidal), XeOF₄ (square pyramidal)"],
["C","Diborane","B₂H₆ has two 3-centre-2-electron 'banana' bonds"],
["C","Inert pair effect","Heavier p-block elements prefer oxidation state two lower than group valency (Tl⁺, Pb²⁺, Bi³⁺)"],
["C","Graphite versus diamond","Graphite: sp², layered, conducts. Diamond: sp³, hardest, insulator"],
["C","KMnO₄ reduction products","Acidic: Mn²⁺; neutral/weakly alkaline: MnO₂; strongly alkaline: MnO₄²⁻"],
["C","Chromate–dichromate equilibrium","Acid: 2CrO₄²⁻ + 2H⁺ → Cr₂O₇²⁻ + H₂O (orange). Base: reverse (yellow)"],
["C","Why d-block compounds are coloured","d–d transitions in partly filled d-orbitals (or charge transfer)"],
["C","Unpaired electrons in Mn²⁺, Fe³⁺, Cu²⁺","Mn²⁺ 5; Fe³⁺ 5; Cu²⁺ 1"],
["C","Metallurgy: roasting, calcination, flotation","Roasting: sulphide ore in air. Calcination: carbonate/hydrate ore, no air. Froth flotation: sulphide ores"],
["C","Hall–Héroult process","Electrolysis of Al₂O₃ in molten cryolite (Na₃AlF₆) with CaF₂ using graphite electrodes"],
["C","Mond and van Arkel processes","Mond: Ni via volatile Ni(CO)₄. Van Arkel: Ti, Zr via volatile iodides on hot filament"],
["C","Zone refining","Used for ultrapure Si, Ge, Ga: impurities concentrate in the molten zone"],
["C","Blast furnace slag","CaO + SiO₂ → CaSiO₃ (flux removes silica gangue)"],
["C","Qualitative analysis: group reagents","I: dil HCl (Pb²⁺, Ag⁺). II: H₂S in acid (Cu²⁺, Cd²⁺). III: NH₄Cl/NH₄OH (Fe³⁺, Al³⁺). IV: H₂S in base (Zn²⁺, Mn²⁺, Ni²⁺, Co²⁺). V: (NH₄)₂CO₃ (Ba²⁺, Sr²⁺, Ca²⁺)"],
["C","Brown ring test","Nitrate + FeSO₄ + conc. H₂SO₄ gives [Fe(H₂O)₅NO]²⁺, a brown ring"],
["C","Chromyl chloride test","Chloride + K₂Cr₂O₇ + conc. H₂SO₄ gives red vapours of CrO₂Cl₂"],
["C","Nessler's reagent","K₂[HgI₄] + KOH gives a brown precipitate/colour with NH₄⁺"],
/* ---------- CHEMISTRY: organic ---------- */
["C","Priority order of functional groups (IUPAC)","Carboxylic acid > sulphonic acid > anhydride > ester > acid halide > amide > nitrile > aldehyde > ketone > alcohol > amine > alkene > alkyne"],
["C","Stability of carbocations and carbanions","Carbocation: 3° > 2° > 1° > CH₃⁺. Carbanion: CH₃⁻ > 1° > 2° > 3°"],
["C","Acidity order","RCOOH > phenol > H₂O > alcohol > terminal alkyne > NH₃ > alkene"],
["C","Basicity of amines in aqueous solution (ethyl)","2° > 3° > 1° > NH₃ (solvation and +I effect); aniline is much weaker"],
["C","Meso compound","Has stereocentres but an internal plane of symmetry, so it is optically inactive"],
["C","Staggered versus eclipsed ethane","Staggered is more stable by ~12 kJ/mol (less torsional strain)"],
["C","Wurtz reaction","2R–X + 2Na (dry ether) → R–R + 2NaX"],
["C","Kharasch (peroxide) effect","HBr adds anti-Markovnikov to alkenes in the presence of peroxides (only HBr)"],
["C","Saytzeff versus Hofmann elimination","Saytzeff: most substituted (stable) alkene. Hofmann: least substituted alkene (bulky base, or quaternary ammonium)"],
["C","Reduction of alkynes","H₂/Lindlar's catalyst → cis-alkene. Na/liq. NH₃ → trans-alkene"],
["C","Kucherov reaction","Alkyne hydration (HgSO₄/H₂SO₄) gives ketone (aldehyde only for ethyne)"],
["C","Friedel–Crafts limitations","Fails on strongly deactivated rings (nitrobenzene) and with amino-groups; alkylation can rearrange"],
["C","Directing effects on benzene","o/p: –OH, –NH₂, –OR, –R. Halogens: o/p but deactivating. m: –NO₂, –CN, –COOH, –CHO, –SO₃H"],
["C","Sandmeyer reaction","ArN₂⁺X⁻ + CuX → ArX (X = Cl, Br, CN)"],
["C","Gattermann–Koch","Benzene + CO + HCl (AlCl₃/CuCl) → benzaldehyde"],
["C","Reimer–Tiemann reaction","Phenol + CHCl₃ + NaOH → salicylaldehyde (ortho; via dichlorocarbene)"],
["C","Kolbe–Schmitt reaction","Sodium phenoxide + CO₂ (125 °C, 5 atm), then H⁺ → salicylic acid"],
["C","Diazotisation conditions","ArNH₂ + NaNO₂ + HCl at 0–5 °C → ArN₂⁺Cl⁻"],
["C","Coupling of diazonium salts","With phenol (mildly basic) or aniline (mildly acidic) gives azo dyes at para position"],
["C","Finkelstein and Swarts reactions","Finkelstein: R–Cl + NaI (acetone) → R–I. Swarts: R–Br + AgF → R–F"],
["C","Williamson ether synthesis","R–ONa + R′–X → R–O–R′ (SN2; best with 1° halide)"],
["C","Lucas test","ZnCl₂/conc. HCl: 3° alcohol turbid immediately; 2° in ~5 min; 1° only on heating"],
["C","Iodoform test","I₂/NaOH with CH₃CO– or CH₃CH(OH)– compounds gives yellow CHI₃"],
["C","Rosenmund reduction","RCOCl + H₂ (Pd/BaSO₄) → RCHO"],
["C","Stephen reaction","RCN + SnCl₂/HCl, then H₃O⁺ → RCHO"],
["C","Etard reaction","Toluene + CrO₂Cl₂, then H₃O⁺ → benzaldehyde"],
["C","Clemmensen versus Wolff–Kishner","Clemmensen: Zn–Hg/conc. HCl (acidic). Wolff–Kishner: N₂H₄/KOH, glycol, heat (basic). Both: C=O → CH₂"],
["C","Hell–Volhard–Zelinsky reaction","RCH₂COOH + X₂/red P → α-halo acid"],
["C","Carbylamine reaction","1° amine + CHCl₃ + KOH → isocyanide (foul smell); test for 1° amines"],
["C","Hinsberg's reagent","C₆H₅SO₂Cl: 1° amine gives soluble sulphonamide, 2° gives insoluble, 3° does not react"],
["C","Gabriel phthalimide synthesis","Phthalimide → N-alkyl phthalimide → hydrolysis gives pure 1° aliphatic amine (not aromatic)"],
["C","Reactivity order of acid derivatives","RCOCl > (RCO)₂O > RCOOR′ > RCONH₂"],
["C","Reactivity towards nucleophilic addition","HCHO > RCHO > R₂C=O > ArCHO > ArCOR"],
["C","Decarboxylation with soda lime","RCOONa + NaOH/CaO → R–H + Na₂CO₃ (one carbon fewer)"],
["C","Kolbe electrolysis","2RCOONa (aq, electrolysis) → R–R + 2CO₂ at anode"],
["C","Benedict's and Fehling's tests","Aliphatic aldehydes give red Cu₂O precipitate; aromatic aldehydes and ketones do not"],
["C","Nylon-6,6 and nylon-6","Nylon-6,6: hexamethylenediamine + adipic acid. Nylon-6: caprolactam"],
["C","Terylene and Bakelite monomers","Terylene: ethylene glycol + terephthalic acid. Bakelite: phenol + formaldehyde"],
["C","Buna-S, Buna-N and neoprene","Buna-S: butadiene + styrene. Buna-N: butadiene + acrylonitrile. Neoprene: chloroprene"],
["C","Natural rubber","cis-1,4-polyisoprene; vulcanised with sulphur to improve strength"],
["C","Thermoplastic versus thermosetting","Thermoplastic: softens on heating (PVC, polythene). Thermosetting: cross-linked, sets permanently (Bakelite)"],
["C","Glucose structure","Pentahydroxy aldehyde (aldohexose); cyclic pyranose forms α and β are anomers"],
["C","Sucrose","α-D-glucose + β-D-fructose via 1,2-glycosidic bond; non-reducing; invert sugar after hydrolysis"],
["C","Starch versus cellulose","Starch: α-glucose (amylose + amylopectin). Cellulose: β-glucose, β-1,4 linkages, unbranched"],
["C","Zwitterion and isoelectric point","Amino acid exists as H₃N⁺–CHR–COO⁻; at its isoelectric point net charge is zero"],
["C","Protein structure levels","Primary: sequence. Secondary: α-helix/β-sheet. Tertiary: 3-D folding. Quaternary: subunit assembly"],
["C","Vitamin deficiency diseases","A: night blindness; B₁: beriberi; C: scurvy; D: rickets; K: blood clotting; B₁₂: pernicious anaemia"],
["C","Base pairing in DNA","A–T (2 H-bonds), G–C (3 H-bonds); RNA has uracil instead of thymine"],
["C","Common drug classes","Aspirin: analgesic/antipyretic; penicillin: antibiotic; ranitidine: antacid; chlorpheniramine: antihistamine"],
["C","Soaps versus detergents","Soap: sodium salt of fatty acid, ineffective in hard water. Synthetic detergents work in hard water"],
["C","Ozone depletion","CFCs release Cl radicals in the stratosphere: Cl• + O₃ → ClO• + O₂, a chain reaction"],
/* ---------- MATHS ---------- */
["M","Double-angle: sin 2A and tan 2A","sin2A = 2sinA cosA = 2tanA/(1 + tan²A); tan2A = 2tanA/(1 − tan²A)"],
["M","cos 3A and tan 3A","cos3A = 4cos³A − 3cosA; tan3A = (3tanA − tan³A)/(1 − 3tan²A)"],
["M","Sum to product (sinC + sinD)","sinC + sinD = 2 sin((C+D)/2) cos((C−D)/2)"],
["M","Product to sum","2 sinA cosB = sin(A+B) + sin(A−B); 2 cosA cosB = cos(A+B) + cos(A−B)"],
["M","General solutions of trig equations","sinθ = sinα → θ = nπ + (−1)ⁿα; cosθ = cosα → θ = 2nπ ± α; tanθ = tanα → θ = nπ + α"],
["M","Sine and cosine rules","a/sinA = b/sinB = c/sinC = 2R; a² = b² + c² − 2bc cosA"],
["M","Area of a triangle","Δ = ½ab sinC = √[s(s−a)(s−b)(s−c)] = rs = abc/4R"],
["M","Inverse trig identities","sin⁻¹x + cos⁻¹x = π/2; tan⁻¹x + cot⁻¹x = π/2"],
["M","Sum of two inverse tangents","tan⁻¹x + tan⁻¹y = tan⁻¹[(x+y)/(1−xy)] if xy < 1"],
["M","Σn, Σn², Σn³","n(n+1)/2; n(n+1)(2n+1)/6; [n(n+1)/2]²"],
["M","Relation between AM, GM, HM of two numbers","GM² = AM × HM; AM ≥ GM ≥ HM"],
["M","Vieta's formulas for a cubic ax³ + bx² + cx + d","Σα = −b/a; Σαβ = c/a; αβγ = −d/a"],
["M","Triangle inequality for complex numbers","|z₁ + z₂| ≤ |z₁| + |z₂|; ||z₁| − |z₂|| ≤ |z₁ − z₂|"],
["M","Argument and modulus of a product","arg(z₁z₂) = arg z₁ + arg z₂; |z₁z₂| = |z₁||z₂|"],
["M","Locus |z − z₁| = |z − z₂|","Perpendicular bisector of the segment joining z₁ and z₂"],
["M","Extreme value of a quadratic ax² + bx + c","Vertex at x = −b/2a; value = −D/4a (min if a > 0, max if a < 0)"],
["M","Middle term(s) of (a + b)ⁿ","n even: T_{n/2+1}. n odd: T_{(n+1)/2} and T_{(n+3)/2}"],
["M","Pascal's identity","ⁿC_r + ⁿC_{r−1} = ⁿ⁺¹C_r; ⁿC_r = ⁿC_{n−r}"],
["M","Circular permutations","(n − 1)! (for necklaces/bracelets divide by 2 again)"],
["M","Identical objects into distinct boxes","Non-negative solutions of x₁+…+x_r = n: ⁿ⁺ʳ⁻¹C_{r−1}"],
["M","Number of derangements","D_n = n!(1 − 1/1! + 1/2! − … + (−1)ⁿ/n!)"],
["M","Number of functions, one-one maps, relations","Functions A→B: nᵐ. One-one: ⁿP_m. Relations: 2^{mn}"],
["M","Inclusion–exclusion for two sets","n(A ∪ B) = n(A) + n(B) − n(A ∩ B)"],
["M","Transpose, symmetric and skew-symmetric","(AB)ᵀ = BᵀAᵀ; A + Aᵀ is symmetric; A − Aᵀ is skew-symmetric"],
["M","adj(adj A) and |adj A|","|adj A| = |A|ⁿ⁻¹; adj(adj A) = |A|ⁿ⁻² A"],
["M","Cayley–Hamilton theorem","Every square matrix satisfies its own characteristic equation"],
["M","Cramer's rule","x = D₁/D, y = D₂/D, z = D₃/D; D = 0 with all Dᵢ = 0 → infinite solutions or none"],
["M","Derivatives of aˣ and logₐx","d/dx aˣ = aˣ ln a; d/dx logₐx = 1/(x ln a)"],
["M","Derivatives of inverse trig functions","sin⁻¹x: 1/√(1−x²); cos⁻¹x: −1/√(1−x²); tan⁻¹x: 1/(1+x²)"],
["M","Parametric differentiation","dy/dx = (dy/dt)/(dx/dt)"],
["M","Rolle's theorem and LMVT","Rolle: f(a) = f(b) ⇒ f′(c) = 0. LMVT: f′(c) = [f(b) − f(a)]/(b − a)"],
["M","L'Hôpital's rule","For 0/0 or ∞/∞: lim f/g = lim f′/g′"],
["M","Second-derivative test","f′(c) = 0, f″(c) > 0 → local min; f″(c) < 0 → local max"],
["M","Tangent and normal slopes","Tangent slope m = dy/dx; normal slope = −1/m"],
["M","Basic integrals of sec² x, sec x tan x","∫sec²x dx = tan x + C; ∫sec x tan x dx = sec x + C; ∫cosec²x dx = −cot x + C"],
["M","∫ dx / (x² − a²)","(1/2a) ln|(x − a)/(x + a)| + C"],
["M","∫ dx / √(x² ± a²)","ln|x + √(x² ± a²)| + C"],
["M","∫ √(a² − x²) dx","(x/2)√(a² − x²) + (a²/2) sin⁻¹(x/a) + C"],
["M","∫ eˣ[f(x) + f′(x)] dx","eˣ f(x) + C"],
["M","Integral over periodic function","∫₀^{nT} f(x) dx = n ∫₀^{T} f(x) dx"],
["M","Wallis integral","∫₀^{π/2} sinⁿx dx = (n−1)(n−3)…/(n(n−2)…) × (π/2 if n even else 1)"],
["M","Area enclosed by an ellipse","π a b"],
["M","Area between curves","∫ₐᵇ [f(x) − g(x)] dx where f ≥ g"],
["M","Solving homogeneous differential equation","Put y = vx so dy/dx = v + x dv/dx, then separate variables"],
["M","Order and degree of a differential equation","Order: highest derivative; degree: its power after clearing radicals/fractions"],
["M","Angle between two lines in 2D","tanθ = |(m₁ − m₂)/(1 + m₁m₂)|"],
["M","Distance between parallel lines","|c₁ − c₂| / √(a² + b²)"],
["M","Family of lines through intersection","L₁ + λL₂ = 0"],
["M","Tangent to a circle at (x₁, y₁)","xx₁ + yy₁ = r² (for x² + y² = r²)"],
["M","Length of tangent and radical axis","Length = √S₁; radical axis: S₁ − S₂ = 0"],
["M","Condition for y = mx + c to touch x² + y² = a²","c² = a²(1 + m²)"],
["M","Tangent to y² = 4ax with slope m","y = mx + a/m; parametric point (at², 2at)"],
["M","Tangency conditions for ellipse and hyperbola","Ellipse: c² = a²m² + b². Hyperbola: c² = a²m² − b²"],
["M","Director circle","Ellipse: x² + y² = a² + b². Hyperbola: x² + y² = a² − b²"],
["M","Latus rectum of an ellipse","2b²/a"],
["M","Rectangular hyperbola","xy = c²: parametric (ct, c/t), asymptotes are the axes, e = √2"],
["M","Direction cosines","l² + m² + n² = 1; direction ratios proportional to (l, m, n)"],
["M","Distance from a point to a plane","|ax₁ + by₁ + cz₁ + d| / √(a² + b² + c²)"],
["M","Angle between a line and a plane","sinθ = |a·n| / (|a||n|)"],
["M","Projection of a on b","(a·b)/|b|"],
["M","Coplanarity of three vectors","[a b c] = 0"],
["M","Vector triple product","a × (b × c) = b(a·c) − c(a·b)"],
["M","Lagrange's identity","|a × b|² = |a|²|b|² − (a·b)²"],
["M","Area of triangle and parallelogram from vectors","Triangle: ½|a × b|. Parallelogram: |a × b|"],
["M","Conditional probability","P(A|B) = P(A ∩ B) / P(B)"],
["M","Probability of at least one success in n trials","1 − qⁿ"],
["M","Variance and standard deviation","σ² = Σx²/n − (Σx/n)²; σ = √variance"],
["M","Expectation of a random variable","E(X) = Σ xᵢpᵢ; Var(X) = E(X²) − [E(X)]²"],
["M","Series expansions of eˣ and ln(1 + x)","eˣ = Σxⁿ/n!; ln(1 + x) = x − x²/2 + x³/3 − … (−1 < x ≤ 1)"],
["M","Series for sin x and cos x","sin x = x − x³/3! + x⁵/5! − …; cos x = 1 − x²/2! + x⁴/4! − …"],
["M","Cauchy–Schwarz inequality","(a₁b₁ + a₂b₂ + …)² ≤ (a₁² + a₂² + …)(b₁² + b₂² + …)"],
["M","Logarithm change of base","logₐb = ln b / ln a = 1/log_b a"],
["M","Domain of inverse trig functions","sin⁻¹, cos⁻¹: [−1, 1]; tan⁻¹, cot⁻¹: ℝ; sec⁻¹, cosec⁻¹: |x| ≥ 1"],
["M","Greatest integer function properties","[x + n] = [x] + n for integer n; [x] + [−x] = −1 if x is not an integer"],
["M","Periodicity of |sin x|, tan x, sin²x","|sin x|: π; tan x: π; sin²x: π; sin x: 2π"],
["M","Sum of interior angles and exterior angles of an n-gon","Interior: (n − 2)π; exterior: always 2π"]
];
window.flashSeed = (window.flashSeed || []);
const seen = new Set(window.flashSeed.map(r => r[0] + '|' + r[1]));
X.forEach(r => { const k = r[0] + '|' + r[1]; if (!seen.has(k)) { seen.add(k); window.flashSeed.push(r); } });
})();
